version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Update 'VARIANT' to pick a version of Python: 3, 3.10, 3.9, 3.8, 3.7, 3.6
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: 3-bullseye
        # Optional Node.js version to install
        # NODE_VERSION: "lts/*"

    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks: 
      - backend_network

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: mysql:latest
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: MYSQLdatabase
      MYSQL_USER: DBuser
      MYSQL_PASSWORD: password

    ports:
     - "3307:3306"

    networks: 
      - backend_network

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

networks:
  backend_network:
    driver: bridge

volumes:
  mysql_data: